version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: payskool_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: payskool
      POSTGRES_PASSWORD: payskool_dev
      POSTGRES_DB: payskool_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U payskool -d payskool_dev']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: payskool_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: payskool_redis_insight
    restart: unless-stopped
    ports:
      - '5540:5540'
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
