// Re-export everything from Prisma client + generated types
export { prisma, default } from './client.js'
export type {
  Workspace,
  User,
  School,
  Membership,
  Invitation,
  Student,
  ParentStudent,
  FeeStructure,
  FeeInstallment,
  StudentFeePlan,
  StudentFeePlanInstallment,
  Transaction,
  TransactionAllocation,
  PaymentWebhookLog,
  NotificationLog,
  Receipt,
  AuditLog,
  OtpCode,
  ImportJob,
  NotificationSettings,
  DailyCashSummary,
  Prisma,
} from '@prisma/client'

export {
  UserRole,
  SchoolType,
  SchoolStatus,
  StudentStatus,
  Gender,
  FeeType,
  InstallmentStatus,
  TransactionStatus,
  TransactionChannel,
  TransactionType,
  PaymentProvider,
  NotificationChannel,
  NotificationStatus,
  MembershipStatus,
  InvitationStatus,
  WorkspacePlan,
  DiscountType,
  StudentFeePlanStatus,
  ImportJobStatus,
} from '@prisma/client'
